vich_uploader:
    db_driver: orm

    mappings:
        certification:
            uri_prefix: /images/certification
            upload_destination: '%kernel.project_dir%/public/images/certification'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
